name: Update Containers

on:
  push:
    branches:
      - main

jobs:
  update-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Build Docker image
        run: docker build -t douglasnobre65/hortofrontend:v1.0 .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push douglasnobre65/hortofrontend:v1.0

      - name: Restart containers in Portainer
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.PORTAINER_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"type":1}' \
          https://portainer.cactustheca.shop/api/endpoints/1/docker/containers/restart
